### PR TITLE
Fix Browser, Google App etc. FC/black screen and stock keyboard FC wi…

### PR DESCRIPTION
**Pull request by aidas957**
…th GApps

Note: keyboard FC fix breaks Gesture Typing (tell people to install Google Keyboard if they want that)
Most internet-requiring apps are using WebView, so add (at least) the Browser fix

### CODE REVIEW

**Comment by aidas957** [comment]
Why?

**Comment by SandPox** [comment]
this is not implement, i'll implement in patch for that, no need to point into separated repository to make sure everything is up-to-date

**Comment by aidas957** [comment]
OK (As for WebView, there is no other easy option, and for LatinIME, just apply my commits in my LatinIME repo)

**Comment by SandPox** [comment]
there is patch from pawitp, don't claim it as yours

**Comment by aidas957** [comment]
That pawitp patch still has a black screen on our devices (GT-S7580/GT-S7582)

**Comment by SandPox** [comment]
it's don't have black screen on mine

**Comment by aidas957** [comment]
We are talking about CM 13

**Comment by SandPox** [comment]
yes, my local testing build don't have that problem, i tested with A-GAPPS 6.0.1

**Comment by aidas957** [comment]
Link?

**Comment by SandPox** [comment]
just wait until stable release

**Comment by aidas957** [comment]
Test link?

**Pull request closed without merging**
